development:
  clients:
    default:
      uri: mongodb+srv://14jdelap:fibzow-1Feqce-cartih@cluster0.tdwqo.mongodb.net/TimeTrackingData
      options:
        server_selection_timeout: 5
test:
  clients:
    default:
      database: time_tracking_app_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
